package model.utilities;

public enum Brand {
	ARMANI, FENDI, VERSACE, BURBERRY, RALPHLAUREN, CHANEL, PRADA, HERMES, GUCCI, LOUISVUITTON, LEVIS, ADIDAS, NIKE,
	UNDERARMOUR, CONVERSE, RAYBAN, COLUMBIA, TIMBERLAND, PUMA, CALVINKLEIN, GAP, VANS, ROLEX, SEIKO, HILFIGER, HNM, ZARA
}
