package model.utilities;

public enum Type {
	HEADWEAR, SCARF, SHIRT, SWEATER, BLOUSE, TSHIRT, JEANS, PANTS, SWEATPANTS, SKIRT, SHORTS, TIGHTS, SOCKS, DRESS, SWIMSUIT, BIKINITOP,
	BIKINIBOTTOM, UNDERWEAR, BRA, COAT, JACKET, HOODIE, VEST, GLOVES, FOOTWEAR, GLASSES, WATCH, NECKLACE, EARRING,
	BRACELET, ANKLET, RING, BELT
}
